### ISSUE TITLE
className is not allowed

### ISSUE THREAD

**Issue by pablobvch** [ponciusz/icomoon-react#18]
Dear @ponciusz, we noticed that you are not allowing className is passed as an attribute in your component.
It would be useful that we can apply such modification to your code.
As an advantage, we would be able to use it with styled-components.
Thanks in advance,
Pablo.

**Comment by ponciusz** [comment]
Hi, @pablobvch I just updated new version https://github.com/ponciusz/icomoon-react/pull/19/commits/1782bd57a122c7ebe86021d47181cb1c89749f7e that's merged PR should solve the problem. Let me know if it's working for you if not please provide some [codesandbox](https://codesandbox.io) example so I can fix it.
Thanks.

**Comment by pablobvch** [comment]
Hello @ponciusz, Thank you so much for the correction. I could update the module and I can the changes.
Kind regards,
Pablo.

**Comment by pablobvch** [comment]
Updated
