### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by codesignist** [ponciusz/icomoon-react#35]
Hi @ponciusz,

It would be very useful to embed the **selection.json** file from CDN.
I found this package but I'm not sure to use it.
https://www.npmjs.com/package/import-cdn-js

What do you think?

**Comment by ponciusz** [comment]
Hi @codesignist `selection.json` can be hosted wherever you want you can store it inside the project which is probably the best because you can quickly update it. The part of the script when you importing it should be in your codebase. the whole point of that library is that you can manage your custom light set of icons which should be easily done thanks to icomoon selection file.

**Comment by codesignist** [comment]
I was thinking to import selection.json file something like this:
```js
import iconSet from "https://somecdnsite.com/selection.json";
```
Is there any way to import like this?

**Comment by ponciusz** [comment]
https://stackoverflow.com/questions/34607252/es6-import-module-from-url

This looks like you will have to deal with asynchronous request. If you really need to get it from cdn just implement request in your app wrap display loading wait when it's ready and pass response json as props or redux store. It will delay the app and you might not see icons when request is not complete. 

What is the reason you want to get it from cdn?

**Comment by codesignist** [comment]
Our designer designs his own special icons. Every time he sends me selection.json file then I download and deploy it to our server. This process is exhausting us.

He can directly upload selection.json file to a server and if I dynamicly use the file without deploy, designer sees his changes directly.

I just want to use this development mode. I don't need on production.

**Comment by ponciusz** [comment]
@codesignist 
I have written some quick [EXAMPLE](https://codesandbox.io/s/icomoon-react-scwek). 

There is probably a much better solution this one was the quickest. Basically I am fetching icons in icon component and saving it into localStorage. if it exists there I am not fetching it again. 

You might implement some additional timestamp check when local storage is older than xxx fetch icons again.

The disadvantage of that method is that you have to wait for icons and you can't see them for the while. You might just place empty SVG with the correct size to avoid UI jumps (empty placeholder will reserve space).

**Comment by codesignist** [comment]
Thank you very much @ponciusz. You are awesome.
