### ISSUE TITLE
Other props not being passed

### ISSUE THREAD

**Issue by gabrielmicko** [ponciusz/icomoon-react#41]
Hey,

I have an issue with other props not being passed down to the element. For example: `data-test`

```
<IcomoonReact
      {...props}
      className={className}
      iconSet={iconSet}
      size={size}
      color={color}
      icon={icon}
      data-test="test"
    />
```

I think this would be useful. I was trying onClick too did not work for the same reason.

**Comment by ponciusz** [comment]
solved in v2.0.20
