### ISSUE TITLE
Please change react and react-dom to peer dependencies, and all others to dev dependencies

### ISSUE THREAD

**Issue by tbroyer** [ponciusz/icomoon-react#42]
Using icomoon-react in a project means installing coveralls, enzyme, typescript, etc. for no good reason.

Also, when using [@hot-loader/react-dom](https://github.com/hot-loader/react-dom) through Yarn name resolution, this will still install the original react-dom in `./node_modules/icomoon-react/node_modules/` in addition to @hot-loader/react-dom in `./node_modules/`. Declaring React as a peer dependency would fix that, as anyone using icomoon-react would have React in their own dependencies as well.

**Comment by tbroyer** [comment]
Wow, it's actually even worse than I thought! Having husky as a dependency means that husky hooks are automatically installed into any git repository that uses icomoon-react!

**Comment by HasanAyan** [comment]
prettier and babel, too. Please move development/build time dependencies into devDependencies. Otherwise, this is causing dependency conflicts

**Comment by ponciusz** [comment]
Sorry guys. Lots of things Baby, crazy covid and new work. thanks for MR
