### ISSUE TITLE
Failed prop type

### ISSUE THREAD

**Issue by Arkellys** [ponciusz/icomoon-react#5]
Hello,

I would like to set `"1em"` as the default size for my icons but I get an error because of the prop type:
`Warning: Failed prop type: Invalid prop `size` of type `string` supplied to `Icon`, expected `number`.`

Because of [this line](https://github.com/ponciusz/icomoon-react/blob/1a66c0332c540b3fce5424b447d992ee63033f0c/dist/IcomoonReact.js#L66) in `IcomoonReact.js`

Would it be possible to take into account this use case of the prop ?

**Comment by ponciusz** [comment]
Hello, @Arkellys this Component is building SVG as output so that is why size is number which is relevant to pixels size={100} will produce squared SVG with 100px width and height. If you need to use em as size probably better will be to use icomoon as font.

**Comment by Arkellys** [comment]
Actually, I would rather use SVG than a font. Knowing that SVG support many others lenght units, wouldn't it be logical to add support for them ?

**Comment by ponciusz** [comment]
Yes, that's right I will implement units support soon. I just did a small test and I can see it will work: https://codepen.io/anon/pen/wQgXba?editors=1100 I did not know that SVG can support EM
